name: try to build project
on:
  push:
     branches: [ main ]

jobs:
  build-project:
    name: setup and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm i
      - run: npm run build
      - run: npm run test
